### ISSUE TITLE
Current maven artefact (0.6.1) is broken

### ISSUE THREAD

**Issue by toff** [unitsofmeasurement/si-units#23]
The currently available maven version (0.6.1) is broken.

Running this simple test
`assertEquals(SI.RADIAN, SI.RADIAN);`

Results in the following exception :
```
java.lang.NoClassDefFoundError: si/uom/quantity/MagnetomotiveForce
	at si.uom.SI.<clinit>(SI.java:105)
	at org.example.uom.uomtest.AppTest.testApp(AppTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:154)
	...
```

pom.xml
```
		<dependency>
			<groupId>si.uom</groupId>
			<artifactId>si-units-java8</artifactId>
			<version>0.6.1</version>
		</dependency>
```

**Comment by keilw** [comment]
Please use Bintray JCenter (see uom-parent it's available to all relevant POMs) in the meantime.  Not sure, why Sonatype did not pick it up then, but requested another sync.

**Comment by cporte** [comment]
0.7 is broken as well, same error

**Comment by keilw** [comment]
Could you try the latest (0.7.1) snapshot in http://oss.jfrog.org/libs-snapshot/si/uom/ ?

**Comment by cporte** [comment]
0.7.1-SNAPSHOT works fine

**Comment by keilw** [comment]
Thanks, including at least https://github.com/unitsofmeasurement/si-units/issues/35 0.7.1 shall be deployed to JCenter and other Maven repositories soon. Hope you can use the Snapshot in the meantime.
